defaults:
    - dataset: kws
    - model: conv-net-trax
    - scheduler: null
    - optimizer: sgd
    - features: mfcc
    - normalizer: fixedpoint
    - module: stream_classifier
    - compress: null
    - trainer: default
    - checkpoint: default
    - backend: null
    - early_stopping: null
    - profiler: null
    - hydra/sweeper: hannah


type: train
experiment_id: nas
output_dir: trained_models
auto_lr: false
seed: [1234]

monitor: ["val_loss", "total_weights", "est_act", "total_macs", "acc_clock_cycles", "acc_power", "acc_area"]


hydra:
  run:
    dir: ${output_dir}/${experiment_id}/${model.name}/
  sweep:
    dir: ${output_dir}/${experiment_id}/${model.name}/

  job_logging:
      handlers:
        console:
          level: CRITICAL

  sweeper:
    optim:
      optimizer: aging_evolution
      population_size: 100
      sample_size: 5
      budget:  2000
      seed: 1234
      num_workers:  5
      bounds:
        val_error: 0.05
        acc_clock_cycles: 20000
        acc_power: 0.00001
        acc_area: 150000




    # default parametrization of the search space
    parametrization:
      model:
        conv:
          min: 2
          max: 6
          choices:
            - target: residual
              stride: 1
              blocks:
                min: 1
                max: 4
                choices:
                  - target: conv1d
                    kernel_size: [1,3,5,7,9]
                    stride: [1]
                    act: [false, true]
                    norm: true
                    out_channels: [8,16,24,32,40,48,56,64]


            #- target: residual
            #  stride: [2,3]
            #  blocks:
            #    min: 1
            #    max: 4
            #    choices:
            #      - target: conv1d
            #        kernel_size: [1,3,5,7,9]
            #        stride: [1,2,3]
            #        act: true
            #        norm: true
            #        out_channels: [8,16,24,32,40,48,56,64]
