defaults:
    - dataset: kws
    - model: tc-res8
    - compress: null
    - scheduler: step
    - optimizer: adam
    - trainer: default
    - checkpoint: default
    - backend: null
    - early_stopping: null
    - profiler: null

type: train
auto_lr: false
batch_size: 128
experiment_id: test
fold_bn: -1
lr: 0.05
seed: 1234
num_workers: 0

#TODO:
dump_test: false
input_file: ''
output_dir: trained_models
