defaults:
    - dataset: kws

auto_lr: false
backend: ''
batch_size: 128
block1_conv_size: 9
block1_output_channels: 24
block1_stride: 2
block2_conv_size: 9
block2_output_channels: 32
block2_stride: 2
block3_conv_size: 9
block3_output_channels: 48
block3_stride: 2
bottleneck:
- 0
- 0
channel_division:
- 2
- 4
clipping_value: 100000
compress: ''
config: ''
conv1_output_channels: 16
conv1_size: 3
conv1_stride: 1
cuda: false
dilation: 1
dropout_prob: 0.5
dump_test: false
early_stopping: 0
experiment_id: test
fast_dev_run: false
fold_bn: -1
fully_convolutional: false
gpu_no:
input_file: ''
inputlayer: true
limits_datasets:
- 1.0
- 1.0
- 1.0
lr: 0.1
lr_decay: 0
lr_gamma: 0.75
lr_patience: 10
lr_scheduler: step
lr_steps:
- 0
lr_stepsize: 0
model: tc-res8
model_class: speech_recognition.models.tc.models.TCResNetModel
model_name: tc-res8
momentum: 0.9
n_epochs: 500
n_labels: 12
num_workers: 32
opt_alpha: 0.99
opt_betas:
- 0.9
- 0.999
opt_eps: 1.0e-06
opt_rho: 0.9
optimizer: sgd
output_dir: trained_models
profile: false
seed: 1234
separable:
- 0
- 0
small: false
tblogger: false
type: train
ultratrail: ''
use_amsgrad: false
use_nesterov: false
vsim: /afs/wsi/es/tools/mentor/questa_core_prime/2019.4.2/questasim/bin/vsim
weight_decay: 1.0e-05
width_multiplier: 1.0
width: 101
height: 40
