defaults:
    - dataset: kws
    - model: tc-res8
    - compress: ''

auto_lr: false
backend: ''
batch_size: 128
experiment_id: test
fold_bn: -1

config: ''
cuda: false
dump_test: false
early_stopping: 0
fast_dev_run: false
gpu_no:
input_file: ''
limits_datasets:
- 1.0
- 1.0
- 1.0
lr: 0.1
lr_decay: 0
lr_gamma: 0.75
lr_patience: 10
lr_scheduler: step
lr_steps:
- 0
lr_stepsize: 0
momentum: 0.9
n_epochs: 500
n_labels: 12
num_workers: 32
opt_alpha: 0.99
opt_betas:
- 0.9
- 0.999
opt_eps: 1.0e-06
opt_rho: 0.9
optimizer: sgd
output_dir: trained_models
profile: false
type: train
ultratrail: ''
use_amsgrad: false
use_nesterov: false
vsim: /afs/wsi/es/tools/mentor/questa_core_prime/2019.4.2/questasim/bin/vsim
weight_decay: 1.0e-05

seed: 1234
