# @package _group_

_target_: torchaudio.transforms.MFCC
sample_rate: ${dataset.samplingrate}
n_mfcc: 40
dct_type: 2
norm: 'ortho'
melkwargs:
    win_length: 250
    hop_length: 10
    n_fft: 480
    f_min: 0.1
    f_max: 100.0
    pad: 0
    n_mels: 40
    power: 2.0
    normalized: False
