# @package _group_

_target_: torchaudio.transforms.MFCC
sample_rate: 16000
n_mfcc: 40
dct_type: 2
norm: 'ortho'
melkwargs:
    win_length: 48
    hop_length: 16
    f_min: 20
    f_max: 4000
    pad: 0
    n_mels: 40
    power: 2.0
    normalized: False
