image: centos:7

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"


cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - yum install epel-release -y
  - yum install git sudo python36 -y
  - yum groupinstall 'Development Tools' -y
  - python3.6 -m ensurepip
  - python3.6 -V # Print out python version for debugging
  - python3.6 -m pip install virtualenv
  - ./bootstrap.sh --venv

test:
  script:
    - echo "Run test"
  tags:
    - docker


