image: centos:7

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  GIT_SUBMODULE_STRATEGY: recursive

cache:
  path:
    - ./cache
    - ./venv

before_script:
  - yum install epel-release -y
  - yum install git sudo python36 -y
  - yum install wget -y
  - yum groupinstall 'Development Tools' -y
  - python3.6 -m ensurepip
  - python3.6 -V # Print out python version for debugging
  - python3.6 -m pip install virtualenv
  # init submodules of project
  - git submodule update --init --recursive
  
  # create virtual environment for python
  - virtualenv venv -p python3.6
  - source venv/bin/activate
  - pip install poetry

  # install and manage dependencies with poetry
  - poetry install
  - cd datasets
  - ./get_datasets.sh
  - cd ..
  

test:
  script:
    - echo "Run test"
    - set -e 
    - source venv/bin/activate
    - python3.6 -m speech_recognition.train --seed 1234 --model tc-res8  --experiment-id ci  --n-epoch=5 --no-cuda
    - python3.6 -m speech_recognition.train --seed 1234 --model tc-res8 --experiment-id ci_prof --n-epoch=1 --profile
  tags:
    - docker


