[tool.poetry]
name = "speech_recognition"
version = "0.1.0"
description = ""
authors = [
    "Christoph Gerum <christoph.gerum@uni-tuebingen.de>",
    "Felix Lorenz <felix.lorenz@student.uni-tuebingen.de>"
]

[tool.poetry.dependencies]
python = ">=3.6.1, <3.9.0"
pwlf = "^2.0.0"
gitdb2 = "2.0.6"
chainmap = "^1.0.3"
redis = "^3.4.1"
torch = "1.6.0"
pytorch-lightning = "^1.0.3"
SoundFile = "^0.10.3"
torchaudio = "^0.6.0"
zipp = "^3.3.1"
bitstring = "^3.1.7"
wfdb = "^3.2.0"
typing-extensions = "^3.7.4"
fsspec = "^0.8.5"
distiller = {path = "./external/distiller", develop=true}

hydra-core = "^1.0.6"
hydra-nevergrad-sweeper = "^1.1.0-rc.1"
hydra-joblib-launcher = "^1.1.0"
hydra-unas-sweeper = {path = "plugins/hydra_unas_sweeper", develop=true}
hydra-submitit-launcher = "^1.1.0"

# optional dependencies
onnx-tf = {git = "https://github.com/onnx/onnx-tensorflow.git", optional = true}
tensorflow-addons = {version = "^0.11.2", optional = true}
onnxruntime = {version = "^1.4.0", optional = true}
tabulate = "^0.8.3"


[tool.poetry.dev-dependencies]
pytest = "4.6.1"
flake8 = "^3.8.3"
pre_commit = "^2.7.1"
black = "^20.8b1"
pytest-cov = "^2.10.1"
rope = "^0.18.0"
mypy = "^0.812"

[tool.poetry.extras]
tf-backend = ["onnx-tf", "tensorflow-addons"]
onnxrt-backend = ["onnxruntime"]

# [[tool.poetry.source]]
# name = "gerum"
# url = "https://atreus.informatik.uni-tuebingen.de/~gerum/dist"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
