[tool.poetry]
name = "speech_recognition"
version = "0.1.0"
description = ""
authors = ["Felix Lorenz <felix.lorenz@student.uni-tuebingen.de>"]

[tool.poetry.dependencies]
python = "^3.6.1"
pwlf = "^2.0.0"
distiller = {path = "./external/distiller"}
gitdb2 = "2.0.6"
chainmap = "^1.0.3"
librosa = "0.6.3"
redis = "^3.4.1"

# due to bug with audioread==2.1.8
# which causes excessive runtimes
audioread = "2.1.6"

pytorch-lightning = "^0.9.0"

# solve "No module named 'numba.decorators'":
numba = "0.48.0"

[tool.poetry.dev-dependencies]
pytest = "4.6.1"
flake8 = "^3.8.3"
pre_commit = "^2.7.1"
black = "^20.8b1"
pytest-cov = "^2.10.1"

[[tool.poetry.source]]
name = "gerum"
url = "https://atreus.informatik.uni-tuebingen.de/~gerum/dist"
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
