[tool.poetry]
name = "srf-poetry"
version = "0.1.0"
description = ""
authors = ["Felix Lorenz <felix.lorenz@student.uni-tuebingen.de>"]

[tool.poetry.dependencies]
python = "^3.6"
pwlf = "^2.0.0"
distiller = {path = "./external/distiller"}
gitdb2 = "2.0.6"

# Poetry importiert tensorflow-estimator==2.2.0rc0
# trotz constraint von tensorflow-gpu:
# tensorflow-estimator = ">=2.1.0rc0,<2.2.0"
# workaround:
#tensorflow-estimator = "2.1.0"

chainmap = "^1.0.3"
librosa = "0.6.3"
redis = "^3.4.1"

# due to bug with audioread==2.1.8
# which causes excessive runtimes
audioread = "2.1.6"

[tool.poetry.dev-dependencies]
pytest = "4.6.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
