# @package _group_

_target_: hannah.models.factory.create_cnn
name: conv_net4_fbgemm
norm:
  target: bn
act:
  target: relu
qconfig:
  _target_: torch.quantization.get_default_qat_qconfig
  backend: fbgemm
conv:
  - target: forward
    stride: 1
    blocks:
      - target: conv1d
        kernel_size: 3
        act: false
        norm: true
        out_channels: 16
  - target: residual
    stride: 2
    blocks:
      - target: conv1d
        kernel_size: 9
        act: true
        norm: true
        out_channels: 24
      - target: conv1d
        kernel_size: 1
        parallel: true
        out_channels: 24
      - target: conv1d
        kernel_size: 9
        act: true
        norm: true
        out_channels: 24
