# @package _group_

# Backend parameters:
#   backend.cols=6
#   backend.rows=None

# Expected results:#   acc_accuracy: 0.0
#   acc_area: 84698.395
#   acc_clock_cycles: 9077.0
#   acc_power: 3.857774222279e-06
#   val_error: 0.06459599733352661

_target_: hannah.models.factory.factory.create_cnn
name: nas2_kws_5uw_lp
norm:
  target: bn
act:
  target: relu
conv:
- blocks:
  - act: true
    kernel_size: 3
    norm: true
    out_channels: 16
    parallel: false
    stride: 1
    target: conv1d
  - act: true
    kernel_size: 5
    norm: true
    out_channels: 56
    parallel: false
    stride: 1
    target: conv1d
  stride: 4
  target: forward
- blocks:
  - act: true
    kernel_size: 1
    norm: true
    out_channels: 28
    parallel: false
    stride: 1
    target: conv1d
  stride: 1
  target: residual
- blocks:
  - act: false
    kernel_size: 9
    norm: true
    out_channels: 20
    parallel: false
    stride: 1
    target: conv1d
  - act: true
    kernel_size: 5
    norm: true
    out_channels: 44
    parallel: false
    stride: 1
    target: conv1d
  - act: false
    kernel_size: 1
    norm: true
    out_channels: 40
    parallel: false
    stride: 1
    target: conv1d
  stride: 4
  target: forward
qconfig:
  _target_: hannah.models.factory.qconfig.get_trax_qat_qconfig
  config:
    bw_b: 0
    bw_f: 6
    bw_w: 6
    noise_prob: 0.7
    power_of_2: false
