

_target_: hannah.models.factory.factory.create_cnn
name: nas_snips_lp
norm:
  target: bn
act:
  target: relu
qconfig:
  _target_: hannah.models.factory.qconfig.get_trax_qat_qconfig
  config:
    bw_b: 0
    bw_w: 4
    bw_f: 4
    power_of_2: false
    noise_prob: 0.7
conv:
- blocks:
  - act: false
    kernel_size: 3
    norm: true
    out_channels: 4
    parallel: false
    stride: 1
    target: conv1d
  - act: true
    kernel_size: 7
    norm: true
    out_channels: 12
    parallel: false
    stride: 1
    target: conv1d
  stride: 6
  target: forward
- blocks:
  - act: false
    kernel_size: 3
    norm: true
    out_channels: 4
    parallel: false
    stride: 1
    target: conv1d
  stride: 6
  target: forward
