

_target_: hannah.models.factory.factory.create_cnn
name: conv_net_trax
norm:
  target: bn
act:
  target: relu
qconfig:
  _target_: hannah.models.factory.qconfig.get_trax_qat_qconfig
  config:
    bw_b: 8
    bw_w: 8
    bw_f: 8
conv:
  - target: forward
    stride: 1
    blocks:
      - target: conv1d
        kernel_size: 3
        act: false
        norm: false
        bias: false
        out_channels: 16
