# @package _group_

gpus: 1
auto_select_gpus: True
limit_train_batches: 1.0
limit_val_batches: 1.0
limit_test_batches: 1.0
max_epochs: 30
default_root_dir: .
fast_dev_run: false
overfit_batches: 0.0
benchmark: False
deterministic: True
