auto_lr: false
backend: ''
batch_size: 128
block1_conv_size: 9
block1_output_channels: 24
block1_stride: 2
block2_conv_size: 9
block2_output_channels: 32
block2_stride: 2
block3_conv_size: 9
block3_output_channels: 48
block3_stride: 2
bottleneck:
- 0
- 0
channel_division:
- 2
- 4
clipping_value: 100000
compress: ''
config: ''
config_hash: fbc1fb576e7100476cb2df517ede67d0fbec9f2b2f0bd93047d6e352e1314076
config_keyword: ''
config_vad: ''
conv1_output_channels: 16
conv1_size: 3
conv1_stride: 1
cuda: false
data_folder: ../../../datasets/speech_commands_v0.02/
dataset: keywords
dataset_cls: speech_recognition.dataset.SpeechCommandsDataset
dev_pct: 10
dilation: 1
dropout_prob: 0.5
dump_test: false
early_stopping: 0
experiment_id: test
extract_loudest: true
fast_dev_run: false
features: mel
fold_bn: -1
freq_max: 4000
freq_min: 20
full_help: false
fully_convolutional: false
gpu_no:
group_speakers_by_id: true
height: 40
input_file: ''
input_file_keyword: ''
input_file_vad: ''
input_length: 16000
inputlayer: true
limits_datasets:
- 1.0
- 1.0
- 1.0
loss: cross_entropy
lr: 0.1
lr_decay: 0
lr_gamma: 0.75
lr_patience: 10
lr_scheduler: step
lr_steps:
- 0
lr_stepsize: 0
model: tc-res8
model_class: speech_recognition.models.tc.models.TCResNetModel
model_name: tc-res8
momentum: 0.9
n_epochs: 500
n_labels: 12
n_mels: 40
n_mfcc: 40
normalize_bits: 0
normalize_max: 256
num_workers: 32
opt_alpha: 0.99
opt_betas:
- 0.9
- 0.999
opt_eps: 1.0e-06
opt_rho: 0.9
optimizer: sgd
output_dir: trained_models
profile: false
samplingrate: 16000
seed: 1234
separable:
- 0
- 0
silence_prob: 0.1
small: false
stride_ms: 10
tblogger: false
test_pct: 10
test_snr: .inf
timeshift_ms: 100
train_pct: 80
train_snr_high: 1000.0
train_snr_low: 0.0
type: train
ultratrail: ''
unknown_prob: 0.1
use_amsgrad: false
use_default_split: false
use_nesterov: false
vsim: /afs/wsi/es/tools/mentor/questa_core_prime/2019.4.2/questasim/bin/vsim
wanted_words:
- 'yes'
- 'no'
- up
- down
- left
- right
- 'on'
- 'off'
- stop
- go
weight_decay: 1.0e-05
width: 101
width_multiplier: 1.0
window_ms: 30
