# @package _group_

_target_: hannah.callbacks.backends.TRaxUltraTrailBackend

teda_dir: ${env:TEDA_HOME,/local/frischkn/neural_networks/teda}
backend_dir: "${backend.teda_dir}/rtl/tc-resnet8-accelerator"

standalone: True
rtl_simulation: False
synthesis: False
postsyn_simulation: False
power_estimation: False
num_inferences: 1
cols: 8
rows: null # Is same as cols
period: 4000
macro_type: "INVECAS"
use_acc_statistic_model: false
use_acc_analytical_model: True
use_acc_teda_data: False
