_target_: hannah.nas.OFANasTrainer
#epochs_warmup: 35
#epochs_kernel_step: 35
#epochs_depth_step: 35
#epochs_width_step: 35
#epochs_dilation_step: 35
epochs_warmup: 5
epochs_kernel_step: 5
epochs_depth_step: 5
epochs_width_step: 5
epochs_dilation_step: 5
elastic_kernels_allowed: True
elastic_depth_allowed: True
elastic_dilation_allowed: True
elastic_width_allowed: True
evaluate: True
random_evaluate: True
random_eval_number: 100
