# @package _group_


_target_: speech_recognition.callbacks.compression.CompressionCallback
fold_bn: 0.9
quantization:
  quantization_type: fixed
  bits_activations: 4
  bits_weights: 4
  bits_bias: 4
pruning:
  target_sparsity: 0.9
