# @package _group_

_target_: hannah.modules.ObjectDetectionModule
num_workers: 0
batch_size: 5
time_masking: 0
frequency_masking: 0

augmentation:
  - augmented_pct: 100
  - reaugment_per_epoch_pct: 50
  - bordersearch_epoch_duration: 5
  - bordersearch_ignore_params: ["draw_fog"]
  - bordersearch_waterlevel: 0.7
  - augmentations: [albumentations]
  - augmentations_pct: [100]
  - rain_drops:
    - angle_rain_streaks: [-45, 45]
    - brightness: [0.2, 2]
    - number_drops: [500, 2000]
    - rain_rate: [1, 60]
    - drop_radius: [0.0004, 0.005]
  - snow:
    - snowfall_rate: [0, 3]
    - car_speed_ms: [0, 13.9]
    - crosswind_speed_ms: [0, 10]
    - draw_fog: [true, false]
  - fog:
    - fog_density: [0, 0.2]
    - fog_sphere: [0.4, 0.7]
  - imagecorruptions:
    - corruption: "snow"
    - severity: [1, 5]
  - albumentations:
    - blur: 30
    - clahe: 50
    - channel_dropout: 2
    - channel_shuffle: 2
    - coarse_dropout: 50
    - downscale: 30
    - equalize: 60
    - gauss_noise: 60
    - hue_saturation_value: 30
    - iso_noise: 40
    - image_compression: 10
    - invert: 5
    - motion_blur: 40
    - posterize: 2
    - rgb_shift: 50
    - random_brightness_contrast: 60
    - random_gamma: 40
    - solarize: 2
    - to_gray: 10
    - to_sepia: 2