# @package _group_

_target_: hannah.modules.ObjectDetectionModule
num_workers: 0
batch_size: 5
time_masking: 0
frequency_masking: 0

augmentation:
  - augmented_pct: 100
  - reaugment_per_epoch_pct: 50
  - bordersearch_epoch_duration: 5
  - bordersearch_ignore_params: ["draw_fog"]
  - bordersearch_waterlevel: 0.7
  - augmentations: [noise]
  - augmentations_pct: [100]
  - rain_drops:
    - angle_rain_streaks: [-45, 45]
    - brightness: [0.2, 2]
    - number_drops: [500, 2000]
    - rain_rate: [1, 60]
    - drop_radius: [0.0004, 0.005]
  - snow:
    - snowfall_rate: [0, 3]
    - car_speed_ms: [0, 13.9]
    - crosswind_speed_ms: [0, 10]
    - draw_fog: [true, false]
  - fog:
    - fog_density: [0, 0.2]
    - fog_sphere: [0.4, 0.7]
  - noise:
    - noise_mode: "gaussian"
    - mean: [0, 0.2]
    - var: [0.5, 2]