# @package _group_

_target_: speech_recognition.models.factory.create_cnn
name: conv_net_inverted
norm:
  target: bn
act:
  target: relu
conv:
  - target: forward
    stride: 1
    blocks:
      - target: conv1d
        kernel_size: 3
        act: false
        norm: true
        out_channels: 16
        upsampling: 2.0
  - target: residual
    stride: 2
    blocks:
      - target: mbconv1d
        kernel_size: 9
        act: true
        norm: true
        out_channels: 16
        upsampling: 2.0
  - target: residual
    stride: 2
    blocks:
      - target: mbconv1d
        kernel_size: 9
        act: true
        norm: true
        out_channels: 16
        upsampling: 2.0
  - target: residual
    stride: 2
    blocks:
      - target: mbconv1d
        kernel_size: 9
        act: true
        norm: true
        out_channels: 16
        upsampling: 2.0
