# @package _group_

# Backend parameters:
#   backend.cols=2
#   backend.rows=None

# Expected results:#   acc_accuracy: 0.0
#   acc_area: 35502.63100000001
#   acc_clock_cycles: -94.0
#   acc_power: 1.1086870159579999e-06
#   val_error: 0.03421902656555176

_target_: speech_recognition.models.factory.factory.create_cnn
name: nas2_wwd_5uw_lp_top1
norm:
  target: bn
act:
  target: relu
conv:
- blocks:
  - act: false
    kernel_size: 1
    norm: true
    out_channels: 4
    parallel: false
    stride: 1
    target: conv1d
  stride: 16
  target: forward
- blocks:
  - act: true
    kernel_size: 9
    norm: true
    out_channels: 16
    parallel: false
    stride: 1
    target: conv1d
  - act: true
    kernel_size: 3
    norm: true
    out_channels: 20
    parallel: false
    stride: 1
    target: conv1d
  stride: 16
  target: forward
- blocks:
  - act: false
    kernel_size: 11
    norm: true
    out_channels: 4
    parallel: false
    stride: 1
    target: conv1d
  - act: true
    kernel_size: 7
    norm: true
    out_channels: 40
    parallel: false
    stride: 1
    target: conv1d
  stride: 1
  target: forward
qconfig:
  _target_: speech_recognition.models.factory.qconfig.get_trax_qat_qconfig
  config:
    bw_b: 0
    bw_f: 4
    bw_w: 6
    noise_prob: 0.7
    power_of_2: false
