# @package _group_

# Backend parameters:
#   backend.cols=6
#   backend.rows=None

# Expected results:#   acc_accuracy: 0.0
#   acc_area: 88449.749
#   acc_clock_cycles: 10081.0
#   acc_power: 4.079514693875001e-06
#   val_error: 0.06009453535079956

_target_: speech_recognition.models.factory.factory.create_cnn
name: nas2_kws_5uw_lp_top2
norm:
  target: bn
act:
  target: relu
conv:
- blocks:
  - act: true
    kernel_size: 3
    norm: true
    out_channels: 16
    parallel: false
    stride: 1
    target: conv1d
  - act: true
    kernel_size: 5
    norm: true
    out_channels: 56
    parallel: false
    stride: 1
    target: conv1d
  stride: 4
  target: forward
- blocks:
  - act: true
    kernel_size: 1
    norm: true
    out_channels: 36
    parallel: false
    stride: 1
    target: conv1d
  stride: 1
  target: residual
- blocks:
  - act: false
    kernel_size: 11
    norm: true
    out_channels: 20
    parallel: false
    stride: 1
    target: conv1d
  - act: true
    kernel_size: 7
    norm: true
    out_channels: 48
    parallel: false
    stride: 1
    target: conv1d
  - act: false
    kernel_size: 1
    norm: true
    out_channels: 40
    parallel: false
    stride: 1
    target: conv1d
  stride: 4
  target: forward
qconfig:
  _target_: speech_recognition.models.factory.qconfig.get_trax_qat_qconfig
  config:
    bw_b: 0
    bw_f: 6
    bw_w: 6
    noise_prob: 0.7
    power_of_2: false
