# @package _group_

_target_: speech_recognition.models.factory.factory.create_cnn
name: nas_vad_ha
norm:
  target: bn
act:
  target: relu
qconfig:
  _target_: speech_recognition.models.factory.qconfig.get_trax_qat_qconfig
  config:
    bw_b: 0
    bw_w: 4
    bw_f: 6
    power_of_2: false
    noise_prob: 0.7
conv:
- blocks:
  - act: false
    kernel_size: 3
    norm: true
    out_channels: 48
    parallel: false
    stride: 1
    target: conv1d
  - target: conv1d
    kernel_size: 9
    stride: 1
    act: true
    parallel: false
    norm: true
    out_channels: 12
  - act: true
    kernel_size: 7
    norm: true
    out_channels: 32
    parallel: false
    stride: 1
    target: conv1d
  stride: 4
  target: forward
- blocks:
  - act: true
    kernel_size: 9
    norm: true
    out_channels: 8
    parallel: false
    stride: 1
    target: conv1d
  stride: 3
  target: residual
