# @package _group_

#cls: speech_recognition.models.wip.models.WIPModel
_target_: speech_recognition.models.wip.models.create
name: wip
min_depth: 2
steps_without_sampling: 9999999
steps_per_kernel_step: 9999999
steps_per_channel_step: 10000
norm_order:
  norm_before_act: true
  norm_after_act: false
# conv layout from conv-net-factory
# to add elastic channel count following a module which is not elastic_conv1d
# an "elastic_channel_helper" module with only a channel_count list may be added after
# the maximum channel count of the elastic helper must match the out_channels of the previous module
conv:
  - target: forward
    stride: 1
    blocks:
      - target: conv1d
        kernel_size: 3
        act: false
        norm: true
        out_channels: 16
  - target: residual1d
    stride: 2
    blocks:
      - target: elastic_conv1d
        kernel_sizes:
          - 9
          - 5
          - 3
          - 1
        act: true
        norm: true
        out_channels:
          - 24
          - 16
          - 8
      - target: conv1d
        kernel_size: 1
        out_channels: 24
      - target: elastic_conv1d
        kernel_sizes:
          - 9
          - 5
          - 3
          - 1
        act: true
        norm: true
        out_channels: 
          - 24
          - 16
          - 8
  - target: residual1d
    stride: 2
    blocks:
      - target: elastic_conv1d
        kernel_sizes:
          - 9
          - 5
          - 3
          - 1
        act: true
        norm: true
        out_channels: 
          - 32
          - 24
          - 16
      - target: conv1d
        kernel_size: 1
        out_channels: 32
      - target: elastic_conv1d
        kernel_sizes:
          - 9
          - 5
          - 3
          - 1
        act: true
        norm: true
        out_channels: 
          - 32
          - 24
          - 16
  - target: residual1d
    stride: 2
    blocks:
      - target: elastic_conv1d
        kernel_sizes:
          - 9
          - 5
          - 3
          - 1
        act: true
        norm: true
        out_channels: 
          - 48
          - 32
          - 24
      - target: conv1d
        kernel_size: 1
        out_channels: 48
      - target: elastic_conv1d
        kernel_sizes:
          - 9
          - 5
          - 3
          - 1
        act: true
        norm: true
        out_channels:
          - 48
          - 32
          - 24
