# @package _group_

#cls: speech_recognition.models.wip.models.WIPModel
_target_: speech_recognition.models.wip.models.create
name: wip
min_depth: 2
steps_without_sampling: 10000
steps_per_kernel_step: 99999
norm_order:
  norm_before_act: true
  norm_after_act: false
# conv layout from conv-net-factory
conv:
  - target: forward
    stride: 1
    blocks:
      - target: conv1d
        kernel_size: 3
        act: false
        norm: true
        out_channels: 16
  - target: residual1d
    stride: 2
    blocks:
      - target: elastic_conv1d
        kernel_sizes:
          - 9
          - 5
          - 3
          - 1
        act: true
        norm: true
        out_channels: 24
      - target: conv1d
        kernel_size: 1
        out_channels: 24
      - target: elastic_conv1d
        kernel_sizes:
          - 9
          - 5
          - 3
          - 1
        act: true
        norm: true
        out_channels: 24
  - target: residual1d
    stride: 2
    blocks:
      - target: elastic_conv1d
        kernel_sizes:
          - 9
          - 5
          - 3
          - 1
        act: true
        norm: true
        out_channels: 32
      - target: conv1d
        kernel_size: 1
        out_channels: 32
      - target: elastic_conv1d
        kernel_sizes:
          - 9
          - 5
          - 3
          - 1
        act: true
        norm: true
        out_channels: 32
  - target: residual1d
    stride: 2
    blocks:
      - target: elastic_conv1d
        kernel_sizes:
          - 9
          - 5
          - 3
          - 1
        act: true
        norm: true
        out_channels: 48
      - target: conv1d
        kernel_size: 1
        out_channels: 48
      - target: elastic_conv1d
        kernel_sizes:
          - 9
          - 5
          - 3
          - 1
        act: true
        norm: true
        out_channels: 48
